#!/usr/bin/env node
/**
 * Documentation generator (single source: code + tokens).
 *
 *   node tools/docs.mjs generate   # (re)write docs/generated/*.md
 *   node tools/docs.mjs check      # fail if generated docs are stale
 *
 * Outputs:
 *   docs/generated/components-api.md   props / events / slots per component
 *   docs/generated/token-reference.md  machine-derived token cheat sheet
 */
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import { tokens } from './design-system.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const componentsDir = path.join(root, 'library/src/main/ets/components');
const outDir = path.join(root, 'docs/generated');
const componentsOut = path.join(outDir, 'components-api.md');
const tokensOut = path.join(outDir, 'token-reference.md');

const AUTOGEN = '<!-- AUTO-GENERATED by tools/docs.mjs — do not edit by hand. Run: npm run docs:generate -->';

// ---------- Component API extraction ----------

function extractBlockComment(lines, structLineIndex) {
  // Walk upward past decorators (@Component/@Entry) to a closing */ block comment.
  let i = structLineIndex - 1;
  while (i >= 0 && (lines[i].trim().startsWith('@') || lines[i].trim() === '')) {
    i--;
  }
  if (i < 0 || !lines[i].trim().endsWith('*/')) {
    return '';
  }
  const end = i;
  let start = i;
  while (start >= 0 && !lines[start].trim().startsWith('/**')) {
    start--;
  }
  if (start < 0) {
    return '';
  }
  return lines.slice(start, end + 1)
    .map((l) => l.trim().replace(/^\/\*\*?/, '').replace(/\*\/$/, '').replace(/^\*\s?/, '').trim())
    .filter((l) => l.length > 0)
    .join(' ');
}

function parseComponent(file) {
  const src = fs.readFileSync(file, 'utf8');
  const lines = src.split('\n');
  const enums = [];
  for (const line of lines) {
    const m = line.match(/^export enum (\w+)\s*\{([^}]*)\}/);
    if (m) {
      enums.push({ name: m[1], members: m[2].split(',').map((s) => s.trim()).filter(Boolean) });
    }
  }
  const structIndex = lines.findIndex((l) => /^export struct (\w+)\s*\{/.test(l));
  if (structIndex < 0) {
    return null;
  }
  const name = lines[structIndex].match(/^export struct (\w+)/)[1];
  const description = extractBlockComment(lines, structIndex);

  const props = [];
  const events = [];
  const slots = [];
  for (let i = structIndex + 1; i < lines.length; i++) {
    const raw = lines[i];
    if (/^\s*build\s*\(/.test(raw) || /^\s*aboutToAppear\s*\(/.test(raw)) {
      break;
    }
    const line = raw.replace(/\/\/.*$/, '').trim();
    if (line.length === 0) {
      continue;
    }
    // Skip framework-managed / private state.
    if (/@StorageLink\(|@StorageProp\(|@State\b|private\s/.test(line)) {
      continue;
    }
    let m = line.match(/^@Prop\s+(\w+)\s*:\s*([^=;]+?)\s*(?:=\s*(.+?))?;/);
    if (m) {
      props.push({ name: m[1], type: m[2].trim(), def: (m[3] ?? '').trim() });
      continue;
    }
    m = line.match(/^@BuilderParam\s+(\w+)\??\s*:\s*(.+?);/);
    if (m) {
      slots.push({ name: m[1], type: m[2].trim() });
      continue;
    }
    m = line.match(/^(on\w+)\??\s*:\s*(.+?);/);
    if (m) {
      events.push({ name: m[1], type: m[2].trim() });
      continue;
    }
  }
  return { name, description, enums, props, events, slots };
}

function mdEscape(text) {
  return text.replace(/\|/g, '\\|');
}

function renderComponent(component) {
  const parts = [`### ${component.name}`, ''];
  if (component.description) {
    parts.push(component.description, '');
  }
  if (component.props.length > 0) {
    parts.push('**Props**', '', '| 属性 | 类型 | 默认值 |', '| --- | --- | --- |');
    for (const p of component.props) {
      parts.push(`| \`${p.name}\` | \`${mdEscape(p.type)}\` | ${p.def ? `\`${mdEscape(p.def)}\`` : '—'} |`);
    }
    parts.push('');
  }
  if (component.events.length > 0) {
    parts.push('**事件**', '', '| 回调 | 签名 |', '| --- | --- |');
    for (const e of component.events) {
      parts.push(`| \`${e.name}\` | \`${mdEscape(e.type)}\` |`);
    }
    parts.push('');
  }
  if (component.slots.length > 0) {
    parts.push('**插槽（@BuilderParam）**', '', '| 名称 | 类型 |', '| --- | --- |');
    for (const s of component.slots) {
      parts.push(`| \`${s.name}\` | \`${mdEscape(s.type)}\` |`);
    }
    parts.push('');
  }
  if (component.enums.length > 0) {
    parts.push('**枚举**', '');
    for (const en of component.enums) {
      parts.push(`- \`${en.name}\`: ${en.members.map((v) => `\`${v}\``).join(' · ')}`);
    }
    parts.push('');
  }
  return parts.join('\n');
}

function renderComponentsDoc() {
  const files = fs.readdirSync(componentsDir)
    .filter((f) => f.endsWith('.ets'))
    .sort();
  const components = files
    .map((f) => parseComponent(path.join(componentsDir, f)))
    .filter((c) => c !== null);

  const header = [
    AUTOGEN,
    '',
    '# 组件 API（自动生成）',
    '',
    `共 ${components.length} 个组件。属性 / 事件 / 插槽由 \`.ets\` 源码解析生成，权威用法见 [10 Components](../10-components.md)。`,
    ''
  ].join('\n');
  return `${header}\n${components.map(renderComponent).join('\n')}`;
}

// ---------- Token reference ----------

function colorRows() {
  const rows = Object.entries(tokens.color).map(([name, token]) => {
    const brands = token.$extensions?.brands;
    const brandNote = brands ? Object.keys(brands).join(', ') : '—';
    return `| \`${name}\` | \`${token.$value.light}\` | \`${token.$value.dark}\` | ${brandNote} |`;
  });
  return ['| Token | Light | Dark | 品牌覆盖 |', '| --- | --- | --- | --- |', ...rows].join('\n');
}

function dimensionRows(group) {
  const rows = Object.entries(group)
    .filter(([name]) => !name.startsWith('$'))
    .map(([name, token]) => {
      const value = token.$value;
      if (typeof value === 'string') {
        return `| \`${name}\` | \`${value}\` |`;
      }
      if (value.comfortable) {
        const superCompact = value.superCompact ?? value.compact;
        return `| \`${name}\` | \`${value.comfortable}\` / \`${value.compact}\` (compact) / \`${superCompact}\` (superCompact) |`;
      }
      return `| \`${name}\` | — |`;
    });
  return ['| Token | 值 |', '| --- | --- |', ...rows].join('\n');
}

function fontRows() {
  const rows = Object.entries(tokens.font)
    .filter(([name]) => !name.startsWith('$') && name !== 'family')
    .map(([name, token]) => {
      const v = token.$value;
      return `| \`${name}\` | ${v.fontSize} | ${v.lineHeight} | ${v.fontWeight} |`;
    });
  return ['| Token | fontSize | lineHeight | fontWeight |', '| --- | --- | --- | --- |', ...rows].join('\n');
}

function motionRows() {
  const rows = Object.entries(tokens.motion).map(([name, token]) =>
    `| \`${name}\` | ${token.$type} | \`${JSON.stringify(token.$value)}\` |`);
  return ['| Token | 类型 | 值 |', '| --- | --- | --- |', ...rows].join('\n');
}

function renderTokenDoc() {
  return [
    AUTOGEN,
    '',
    '# Token 速查（自动生成）',
    '',
    '单一事实来源：`tokens/design-tokens.json`。规范见 [16 Design Token](../16-design-token.md)、主题见 [19 Theming](../19-theming.md)。',
    '',
    '## Color',
    '',
    colorRows(),
    '',
    '## Spacing',
    '',
    dimensionRows(tokens.space),
    '',
    '## Radius',
    '',
    dimensionRows(tokens.radius),
    '',
    '## Icon',
    '',
    dimensionRows(tokens.icon),
    '',
    '## Size',
    '',
    dimensionRows(tokens.size),
    '',
    '## Typography',
    '',
    `字体族：\`${tokens.font.family.$value}\``,
    '',
    fontRows(),
    '',
    '## Motion',
    '',
    motionRows(),
    ''
  ].join('\n');
}

// ---------- CLI ----------

function targets() {
  return [
    [componentsOut, renderComponentsDoc()],
    [tokensOut, renderTokenDoc()]
  ];
}

function generate() {
  fs.mkdirSync(outDir, { recursive: true });
  for (const [file, content] of targets()) {
    fs.writeFileSync(file, content);
  }
  console.log('Generated docs/generated/*.md from code and tokens.');
}

function check() {
  const failures = [];
  for (const [file, content] of targets()) {
    const actual = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
    if (actual !== content) {
      failures.push(`${path.relative(root, file)} is stale. Run: npm run docs:generate`);
    }
  }
  if (failures.length > 0) {
    console.error(failures.join('\n'));
    process.exit(1);
  }
  console.log('Generated docs are in sync.');
}

const command = process.argv[2] ?? 'check';
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  if (command === 'generate') {
    generate();
  } else if (command === 'check') {
    check();
  } else {
    console.error(`Unknown command: ${command}`);
    process.exit(1);
  }
}

export { parseComponent, renderComponentsDoc, renderTokenDoc };
